platform: Any CPU

configuration: Debug

build:
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy

deploy:
    # Web Deploy deployment provider settings
  - provider: WebDeploy
    server: http://web01.vcloud01.nextchapter-ecommerce.com/MSDEPLOYAGENTSERVICE
    website: development.nextchapter-ecommerce.com
    username: Administrator
    password: rAm8fw4yxnmo
    ntlm: true
    remove_files: true
    app_offline: false
    on:
      branch: master